### ISSUE TITLE
Params

### ISSUE THREAD

**Issue by prono69** [RaphielHS/akaneko-wrapper#1]
Bro. Do you know how to get all endpoints/params of your api ? :blush:

_Sent from my Redmi Note 4 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by RaphielHS** [comment]
Do you mean all of the functions?
If so, i'll make the code later.

**Comment by prono69** [comment]
How to contact you ? You have any discord channel ?

**Comment by RaphielHS** [comment]
I don't have a discord server, but my discord tag is **Raphiel#4045**
