### ISSUE TITLE
Uhhh.. What?

### ISSUE THREAD

**Issue by Motzumoto** [RaphielHS/akaneko-wrapper#2]
The usages make no sense, based on what you said on the pypi page the way its used is like this 

```py
await akaneko.neko
``` 
or 
```py
await akaneko.neko()
```
 it makes no sense, please update them to make more sense and add better documentation 

[Image of us evaling code](https://zoe.is-super-sexy.xyz/vp8ruh.png)

```py
Traceback (most recent call last):
  File "/home/container/Cogs/admin.py", line 200, in eval
    ret = await func()
  File "<string>", line 3, in func
AttributeError: module 'akaneko' has no attribute 'neko'
```

EDIT: [This isnt even an API, its a middle man](https://zoe.is-super-sexy.xyz/uob2rq.png)

**Comment by RaphielHS** [comment]
Yea, update will come soon, like, Really Really soon

**Comment by RaphielHS** [comment]
The Update has been released, Please Update the wrapper
