### ISSUE TITLE
Your discord bot example doesn't work

### ISSUE THREAD

**Issue by Motzumoto** [RaphielHS/akaneko-wrapper#3]
[Image here](https://zoe.plz-fuck.me/iIjKP4t)

I don't think I'm doing anything wrong, but then again I might be. If I am please let me know

Also, update your repo to let people know you're not accepting friend requests lmfao
[Click Me](https://zoe.plz-fuck.me/n91FX9C)

[I do have the package installed](https://zoe.plz-fuck.me/euDsU8q)

**Comment by RaphielHS** [comment]
Oh, yea sorry, i'll look into it! Thanks

**Comment by RaphielHS** [comment]
Sorry for the late reply, i found the issue, and i'll fix it right away, Thanks for reporting!
